name: Build Testing Docker Image
run-name: Build Testing Docker Image

on:
  push:
    branches:
      - development

jobs:
  build_image:
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: RUN docker build
        run: sudo docker build --tag shared.docker.josian.nl/mcs/tracker:dev .
      - name: Login to registry
        run: >
          echo ${{ secrets.REGISTRY_JOSIAN_PASSWORD }}
          | sudo docker login shared.docker.josian.nl
          -u ${{ secrets.REGISTRY_JOSIAN_USERNAME }} --password-stdin
      - name: Push to registry
        run: sudo docker push shared.docker.josian.nl/mcs/tracker:dev
        
